name: Build and deploy Vite app to Azure Web App - bears-pts-web

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read

    steps:
      - uses: actions/checkout@v4

      - name: Set up Node.js version
        uses: actions/setup-node@v3
        with:
          node-version: '20.x'
          cache: 'npm'

      - name: npm install and build
        env:
          VITE_EMAILJS_SERVICE_ID: ${{ vars.VITE_EMAILJS_SERVICE_ID }}
          VITE_EMAILJS_CONTACT_TEMPLATE_ID: ${{ vars.VITE_EMAILJS_CONTACT_TEMPLATE_ID }}
          VITE_EMAILJS_BOOKING_TEMPLATE_ID: ${{ vars.VITE_EMAILJS_BOOKING_TEMPLATE_ID }}
          VITE_EMAILJS_CAREER_TEMPLATE_ID: ${{ vars.VITE_EMAILJS_CAREER_TEMPLATE_ID }}
          VITE_EMAILJS_PUBLIC_KEY: ${{ vars.VITE_EMAILJS_PUBLIC_KEY }}
        run: |
          npm ci --prefer-offline --no-audit
          npm run build

      - name: List files before upload
        run: |
          echo "=== Files in root directory ==="
          ls -la
          echo "=== Checking if server.cjs exists ==="
          ls -la server.cjs || echo "server.cjs not found"

          echo "=== Checking dist directory ==="
          ls -la dist/

      - name: Upload artifact for deployment job
        uses: actions/upload-artifact@v4
        with:
          name: node-app
          path: |
            ./dist
            ./server.cjs
            ./package.json
            ./package-lock.json
            ./web.config

  deploy:
    runs-on: ubuntu-latest
    needs: build
    
    steps:
      - name: Download artifact from build job
        uses: actions/download-artifact@v4
        with:
          name: node-app

      - name: Install production dependencies
        run: |
          npm ci --only=production

      - name: List files after download
        run: |
          echo "=== Files in deployment directory ==="
          ls -la
          echo "=== Checking if server.cjs exists in deployment ==="
          ls -la server.cjs || echo "server.cjs not found in deployment"
          echo "=== Checking node_modules ==="
          ls -la node_modules/ || echo "node_modules not found"


      - name: 'Deploy to Azure Web App'
        id: deploy-to-webapp
        uses: azure/webapps-deploy@v3
        with:
          app-name: 'bears-pts-web'
          slot-name: 'Production'
          package: .
          publish-profile: ${{ secrets.AZUREAPPSERVICE_PUBLISHPROFILE_08E27CC354B54757B48EE09E520F9F90 }}
